In [1]:
"""
Feature Engineering

Goal:
- Prepare dataset for modeling
- Create useful features
- Remove irrelevant columns
"""

import pandas as pd

In [2]:
"""
Load churn dataset.
"""

df = pd.read_csv("../data/interim/bank_churn_standardized.csv")

df.head()

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
"""
Remove columns that do not help prediction.
"""

df = df.drop(columns=["rownumber", "customerid", "surname"])

In [4]:
"""
Convert categorical variables into numeric form.
"""

df = pd.get_dummies(df, columns=["geography", "gender"], drop_first=True)

In [5]:
"""
Create useful derived features.
"""

# Balance per product
df["balance_per_product"] = df["balance"] / (df["numofproducts"] + 1)

# Credit score per age
df["credit_per_age"] = df["creditscore"] / (df["age"] + 1)

# Tenure per age
df["tenure_per_age"] = df["tenure"] / (df["age"] + 1)

In [6]:
"""
Check final dataset.
"""

df.head()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,geography_Germany,geography_Spain,gender_Male,balance_per_product,credit_per_age,tenure_per_age
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False,0.00,14.395349,0.046512
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False,41903.93,14.476190,0.023810
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False,39915.20,11.674419,0.186047
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False,0.00,17.475000,0.025000
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False,62755.41,19.318182,0.045455

In [7]:
"""
Save processed dataset for modeling.
"""

df.to_csv("../data/processed/churn_features.csv", index=False)

print("Saved to processed folder")

Saved to processed folder